# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2009-2018, Ask Solem & contributors
# This file is distributed under the same license as the Celery package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2019.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Celery 4.3\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-05-22 13:45+0900\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.6.0\n"

#: ../reference/celery.exceptions.rst:3
msgid "``celery.exceptions``"
msgstr ""

#: celery.exceptions:1 of
msgid "Celery error types."
msgstr ""

#: celery.exceptions:4 of
msgid "Error Hierarchy"
msgstr ""

#: celery.exceptions:36 of
msgid ":exc:`Exception`"
msgstr ""

#: celery.exceptions:22 of
msgid ":exc:`celery.exceptions.CeleryError`"
msgstr ""

#: celery.exceptions:8 of
msgid ":exc:`~celery.exceptions.ImproperlyConfigured`"
msgstr ""

#: celery.exceptions:9 of
msgid ":exc:`~celery.exceptions.SecurityError`"
msgstr ""

#: celery.exceptions:12 of
msgid ":exc:`~celery.exceptions.TaskPredicate`"
msgstr ""

#: celery.exceptions:11 of
msgid ":exc:`~celery.exceptions.Ignore`"
msgstr ""

#: celery.exceptions:12 of
msgid ":exc:`~celery.exceptions.Reject`"
msgstr ""

#: celery.exceptions:13 of
msgid ":exc:`~celery.exceptions.Retry`"
msgstr ""

#: celery.exceptions:22 of
msgid ":exc:`~celery.exceptions.TaskError`"
msgstr ""

#: celery.exceptions:15 of
msgid ":exc:`~celery.exceptions.QueueNotFound`"
msgstr ""

#: celery.exceptions:16 of
msgid ":exc:`~celery.exceptions.IncompleteStream`"
msgstr ""

#: celery.exceptions:17 of
msgid ":exc:`~celery.exceptions.NotRegistered`"
msgstr ""

#: celery.exceptions:18 of
msgid ":exc:`~celery.exceptions.AlreadyRegistered`"
msgstr ""

#: celery.exceptions:19 of
msgid ":exc:`~celery.exceptions.TimeoutError`"
msgstr ""

#: celery.exceptions:20 of
msgid ":exc:`~celery.exceptions.MaxRetriesExceededError`"
msgstr ""

#: celery.exceptions:21 of
msgid ":exc:`~celery.exceptions.TaskRevokedError`"
msgstr ""

#: celery.exceptions:22 of
msgid ":exc:`~celery.exceptions.InvalidTaskError`"
msgstr ""

#: celery.exceptions:23 of
msgid ":exc:`~celery.exceptions.ChordError`"
msgstr ""

#: celery.exceptions:31 of
msgid ":class:`kombu.exceptions.KombuError`"
msgstr ""

#: celery.exceptions:25 of
msgid ":exc:`~celery.exceptions.OperationalError`"
msgstr ""

#: celery.exceptions:27 of
msgid ""
"Raised when a transport connection error occurs while sending a message "
"(be it a task, remote control command error)."
msgstr ""

#: celery.exceptions:31 of
msgid ""
"This exception does not inherit from "
":exc:`~celery.exceptions.CeleryError`."
msgstr ""

#: celery.exceptions:36 of
msgid "**billiard errors** (prefork pool)"
msgstr ""

#: celery.exceptions:34 of
msgid ":exc:`~celery.exceptions.SoftTimeLimitExceeded`"
msgstr ""

#: celery.exceptions:35 of
msgid ":exc:`~celery.exceptions.TimeLimitExceeded`"
msgstr ""

#: celery.exceptions:36 of
msgid ":exc:`~celery.exceptions.WorkerLostError`"
msgstr ""

#: celery.exceptions:37 of
msgid ":exc:`~celery.exceptions.Terminated`"
msgstr ""

#: celery.exceptions:42 of
msgid ":class:`UserWarning`"
msgstr ""

#: celery.exceptions:42 of
msgid ":class:`~celery.exceptions.CeleryWarning`"
msgstr ""

#: celery.exceptions:40 of
msgid ":class:`~celery.exceptions.AlwaysEagerIgnored`"
msgstr ""

#: celery.exceptions:41 of
msgid ":class:`~celery.exceptions.DuplicateNodenameWarning`"
msgstr ""

#: celery.exceptions:42 of
msgid ":class:`~celery.exceptions.FixupWarning`"
msgstr ""

#: celery.exceptions:43 of
msgid ":class:`~celery.exceptions.NotConfigured`"
msgstr ""

#: celery.exceptions:48 of
msgid ":exc:`BaseException`"
msgstr ""

#: celery.exceptions:48 of
msgid ":exc:`SystemExit`"
msgstr ""

#: celery.exceptions:46 of
msgid ":exc:`~celery.exceptions.WorkerTerminate`"
msgstr ""

#: celery.exceptions:47 of
msgid ":exc:`~celery.exceptions.WorkerShutdown`"
msgstr ""

#: celery.exceptions.CeleryWarning:1 of
msgid "Base class for all Celery warnings."
msgstr ""

#: celery.exceptions.AlwaysEagerIgnored:1 of
msgid "send_task ignores :setting:`task_always_eager` option."
msgstr ""

#: celery.exceptions.DuplicateNodenameWarning:1 of
msgid "Multiple workers are using the same nodename."
msgstr ""

#: celery.exceptions.FixupWarning:1 of
msgid "Fixup related warning."
msgstr ""

#: celery.exceptions.NotConfigured:1 of
msgid "Celery hasn't been configured, as no config module has been found."
msgstr ""

#: celery.exceptions.CeleryError:1 of
msgid "Base class for all Celery errors."
msgstr ""

#: celery.exceptions.ImproperlyConfigured:1 of
msgid "Celery is somehow improperly configured."
msgstr ""

#: celery.exceptions.SecurityError:1 of
msgid "Security related exception."
msgstr ""

#: celery.exceptions.OperationalError:1 of
msgid "Recoverable message transport connection error."
msgstr ""

#: celery.exceptions.TaskPredicate:1 of
msgid "Base class for task-related semi-predicates."
msgstr ""

#: celery.exceptions.Ignore:1 of
msgid "A task can raise this to ignore doing state updates."
msgstr ""

#: celery.exceptions.Reject:1 of
msgid "A task can raise this if it wants to reject/re-queue the message."
msgstr ""

#: celery.exceptions.Retry:1 of
msgid "The task is to be retried later."
msgstr ""

#: celery.exceptions.Retry.exc:1 of
msgid "Exception (if any) that caused the retry to happen."
msgstr ""

#: celery.exceptions.Retry.message:1 of
msgid "Optional message describing context of retry."
msgstr ""

#: celery.exceptions.Retry.when:1 of
msgid ""
"Time of retry (ETA), either :class:`numbers.Real` or "
":class:`~datetime.datetime`."
msgstr ""

#: celery.exceptions.TaskError:1 of
msgid "Task related errors."
msgstr ""

#: celery.exceptions.QueueNotFound:1 of
msgid "Task routed to a queue not in ``conf.queues``."
msgstr ""

#: celery.exceptions.IncompleteStream:1 of
msgid "Found the end of a stream of data, but the data isn't complete."
msgstr ""

#: celery.exceptions.NotRegistered:1 of
msgid "The task ain't registered."
msgstr ""

#: celery.exceptions.AlreadyRegistered:1 of
msgid "The task is already registered."
msgstr ""

#: celery.exceptions.TimeoutError:1 of
msgid "The operation timed out."
msgstr ""

#: celery.exceptions.MaxRetriesExceededError:1 of
msgid "The tasks max restart limit has been exceeded."
msgstr ""

#: celery.exceptions.TaskRevokedError:1 of
msgid "The task has been revoked, so no result available."
msgstr ""

#: celery.exceptions.InvalidTaskError:1 of
msgid "The task has invalid data or ain't properly constructed."
msgstr ""

#: celery.exceptions.ChordError:1 of
msgid "A task part of the chord raised an exception."
msgstr ""

#: celery.exceptions.SoftTimeLimitExceeded:1 of
msgid ""
"The soft time limit has been exceeded. This exception is raised to give "
"the task a chance to clean up."
msgstr ""

#: celery.exceptions.TimeLimitExceeded:1 of
msgid "The time limit has been exceeded and the job has been terminated."
msgstr ""

#: celery.exceptions.WorkerLostError:1 of
msgid "The worker processing a job has exited prematurely."
msgstr ""

#: celery.exceptions.Terminated:1 of
msgid "The worker processing a job has been terminated by user request."
msgstr ""

#: celery.exceptions.CPendingDeprecationWarning:1 of
msgid "Warning of pending deprecation."
msgstr ""

#: celery.exceptions.CDeprecationWarning:1 of
msgid "Warning of deprecation."
msgstr ""

#: celery.exceptions.WorkerShutdown:1 of
msgid "Signals that the worker should perform a warm shutdown."
msgstr ""

#: celery.exceptions.WorkerTerminate:1 of
msgid "Signals that the worker should terminate immediately."
msgstr ""

